### ISSUE TITLE
Change MTI cipher suites to match non-requirement for DTLS 1.0

### ISSUE THREAD

**Issue by ekr** [rtcweb-wg/security-arch#17]

**Comment by alvestrand** [comment]
Tickling this issue.

Current text (editor's draft) is

All implementations MUST implement DTLS 1.0, with the cipher suite TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA and the DTLS-SRTP protection profile SRTP_AES128_CM_HMAC_SHA1_80. Implementations SHOULD implement DTLS 1.2 with the TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 cipher suite. Implementations MUST favor cipher suites which support PFS over non-PFS cipher suites and SHOULD favor AEAD over non-AEAD cipher suites. [[OPEN ISSUE: Should we require ECDSA? Waiting for WG Consensus.]]

Going to publication with this open issue seems like a Bad Idea.

**Comment by martinthomson** [comment]
I think that the actual editors draft is OK, ekr merged #33 a while ago.
