### ISSUE TITLE
One DTLS connection per component

### ISSUE THREAD

**Issue by martinthomson** [rtcweb-wg/security-arch#27]
RFC 5764 rather optimistically describes how the same DTLS handshake can be used to key SRTP for RTP and RTCP even if these are on different components (i.e., `a=rtcpmux` is not negotiated).  This is not what anyone does.

Mandate precisely one handshake per component.

**Comment by bifurcation** [comment]
FROM IETF100: Don't.

**Comment by fluffy** [comment]
Given we don't allow rtcpmux in WEbRTC. This is sort of irrelevant and we can say it never happens just don't do it.

**Comment by ekr** [comment]
I actually thought this was pretty clear before, but I've added the term component to make it clear.

I don't understand @fluffy's comment. We absolutely allow rtcpmux in WebRTC, but it's still possible to not have it (browsers aren't forbidden to support it).
