### ISSUE TITLE
Open Source WebRTC IdP

### ISSUE THREAD

**Issue by Pierpaolo1992** [rtcweb-wg/security-arch#36]
Hi,

i'm a student of University of Naples "Federico II", and i'm working about my master thesis, that concerns about performance analysis in two different streaming technologies: DASH and WebRTC, in the context of Digital Rights Management.
About WebRTC-part, i'm using Janus (http://janus.conf.meetecho.com) as WebRTC gateway; now i have to use a simply Identity Provider for WebRTC.

I've read draft in IETF about WebRTC security architecture, W3 specs about APIs for communications with an IdP and some dratf/papers about identity management in WebRTC context.

My questions is:

How could i implement a simply IdP? My teacher told me about Oauth, but i'm not very expert about identity provider management.

At the state of art, is there something ready-to-use? I hope that answer is "yes" :) 

Sincerly,

Best regards.

**Comment by vasilakisfil** [comment]
Not as far as I know, extending an OAuth2 server to support the well-known URI requirements for WebRTC would make much sense though. You can find more info here: http://w3c.github.io/webrtc-pc/#sec.identity-proxy.
