### ISSUE TITLE
For identity in the SDP: describe how multiple identity attributes work, as well as parsing of identity

### ISSUE THREAD

**Issue by stefhak** [rtcweb-wg/security-arch#37]
From https://www.ietf.org/mail-archive/web/rtcweb/current/msg16306.html:
> Hi,
>
> after some discussing in in W3C webrtc-pc [1] and JSEP [2][3][4] github 
repos it seems the conclusion is that how identity is handled carried in 
the SDP, and how identity in the SDP is parsed, and how multiple 
identity attributes (if we are to support that) should be describe in 
draft-ietf-rtcweb-security-arch [5].
>
> Identity in the SDP is currently described in 
draft-ietf-rtcweb-security-arch, but only for a single identity 
attribute, and parsing is not described, so it needs to be updated.
>
> I decided to send this to the list as the activity level at the github 
repo [6] for draft-ietf-rtcweb-security-arch seems to be low (indicating 
the action happens elsewhere).
> 
> Stefan
>
>
> [1] https://github.com/w3c/webrtc-pc/issues/964
[2] https://github.com/rtcweb-wg/jsep/issues/546
[3] 
https://github.com/rtcweb-wg/jsep/commit/a40fb5101ae530e97cea2073b507d7b417df9e49
[4] https://github.com/rtcweb-wg/jsep/issues/601
[5] https://tools.ietf.org/html/draft-ietf-rtcweb-security-arch
[6] https://github.com/rtcweb-wg/security-arch

**Comment by bifurcation** [comment]
FROM IETF100: EKR just needs to write some crap

**Comment by fluffy** [comment]
1) only put 1 in 2) semantics undefined if more than one 3) implementations only need to process one

**Comment by ekr** [comment]
@martinthomson: PTAL
