### ISSUE TITLE
Lacking ref and clear naming of Security Descriptions in MUST NOT be offered

### ISSUE THREAD

**Issue by gloinul** [rtcweb-wg/security-arch#40]
In Section 5.5 the following sentence exist:

WebRTC implementations MUST
   NOT offer SDES or select it if offered.

I think SDES should be clarified to mean SDP Security Descriptions and include a reference to RFC 4568. This to avoid any confusion with other SDES usage, including RTP SDES items.

**Comment by ekr** [comment]
Fixed.
