### ISSUE TITLE
Determining the IdP URI

### ISSUE THREAD

**Issue by soareschen** [rtcweb-wg/security-arch#43]
In section 5.6.5.  Determining the IdP URI:

> For example, for the IdP "identity.example.com" and the protocol "example", the URL would be:
>    https://example.com/.well-known/idp-proxy/example
> The IdP MAY redirect requests to this URL, but they MUST retain the "https" scheme.  This changes the effective origin of the IdP, but not the domain of the identities that the IdP is permitted to assert and validate.  I.e., the IdP is still regarded as authoritative for the original domain.

I think the paragraph is a bit confusing. If the IdP domain is identity.example.com, then the URL should be https://identity.example.com/.well-known/idp-proxy/example. 

The response from that URL MAY redirect to https://example.com/.well-known/idp-proxy/example, or it could also be some totally unrelated URL, such as https://trusted.net/not-well-known/idp, as long as the protocol is https. Is that correct?

**Comment by martinthomson** [comment]
Yes, that is correct (there is an error, and the totally unrelated URL can be redirected to).

**Comment by bifurcation** [comment]
Yes, it can be redirected, subject to the normal rules about HTTPS redirects (e.g., no insecure redirects).

**Comment by ekr** [comment]
Fixed
