### ISSUE TITLE
Use the usual headings for new SDP attributes

### ISSUE THREAD

**Issue by martinthomson** [rtcweb-wg/security-arch#76]
As @cdh4u pointed out in a review, these would be useful.

X.1  Generating the Initial Offer
X.2  Generating the Answer
X.3  Offerer Processing of the Answer
X.4  Modifying the Session

I think that the second is redundant with the first and third (generating answers and offers are the same always, as is handling a description).  The modification section has some new requirements.  Though it might be a constraint of the WebRTC API, we don't currently allow identity to change once set.  We'll need some language around that.

**Comment by cdh4u** [comment]
What about call transfers etc (read: 3pcc)? Perhaps a browser client, using the WebRTC API, can't do it, but the remote endpoint may. But, what is the browser client supposed to do if the remote peer changes its identity (perhaps due to yet another 3PCC case...)?

**Comment by martinthomson** [comment]
A browser will refuse the SDP if the identity changes.  That's been part of the WebRTC spec for ages.

**Comment by cdh4u** [comment]
Then, as far as O/A is concerned, if an offerer tries to change the identity, but the answerer does not support/accept it, the offer must be rejected.
