### ISSUE TITLE
Prohibit false start.

### ISSUE THREAD

**Issue by ekr** [rtcweb-wg/security-arch#82]
We should prohibit false start.

**Comment by ekr** [comment]
Because the DTLS-SRTP cipher negotiation is not protected until the Finished.

**Comment by martinthomson** [comment]
That is covered by the false start RFC adequately in my view.

**Comment by ekr** [comment]
Which section do you believe covers it?

**Comment by martinthomson** [comment]
Well, I guess that https://tools.ietf.org/html/rfc7918#section-5.3 covers cipher negotiation, but I would concede that it's probably more mechanical and less about the underlying principles.

**Comment by ekr** [comment]
Yes, and so consider the case where you are negotiating both double and
regular SRTP....

-Ekr

**Comment by seanturner** [comment]
I tend to agree that we should include a reason in #83.
